### ISSUE TITLE
** Critical Issue ** I want your phone call **

### ISSUE THREAD

**Issue by BeiZhouLiu** [GuruJustin/Dapp-Hardhat#3]
Hi bro.

About outsourceing, it is very good news for me.
Are you preparing for blockchain?
Ok, good.
It will be great helpful if you provide me 3D architecture projects as much as possible, here I have some talent developers and I will be happy with the fee what I will take. (I am thinking about 40%).

And here I have very very important problem.
Can you download some android apk games ?
If you have a look on appstore or playgoogle.com then you will see many games that are free or need payment.
I want non-free offline games that have big size.

Here is my requirements in detail.

- Need about 10 ~ 20 android games.
- Offline games
- Only the games that has cost. (it will not heavy cost . less than $5 for each)
- big sized games are welcome. ( 200MB ~ 2GB for each)
I know you don't have much time but plz consider that this issue is very important for me.

**Comment by GuruJustin** [comment]
Hi BeiZhouLIu.

Got what you mean.
Let me answer.

1. 3D: I don't have any project for now but would be in soon. all of them are related to blockchain,
2. Android Games: Need to know what are you going to do with that?
    Porting and launching on your side?

**Comment by GuruJustin** [comment]
Regarding the skype.

I think it's would be better to talk on here.
Best

**Comment by BeiZhouLiu** [comment]
https://github.com/GuruJustin/gurujustin/issues/2

this was my last issue.
let us close this issue and continue on that.
